### ISSUE TITLE
duplicate accounts created for what appears to be a single sign up

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#548] opened 2015-02-03 21:44 UTC
With 0.0.30.1, Open Opportunities, we saw a user sign up with two accounts created -- the time stamps lead me to believe that this was a single user action that resulted in two records being created by the software:

![image](https://cloud.githubusercontent.com/assets/41906/6030197/b4116e12-abaa-11e4-9ff5-6af6a1d67296.png)

I crossed out the specific name, but it's same name, same email address.

**Comment by ultrasaurus** [comment] 2015-02-03 21:44
adding to the current milestone just because we're looking at a bunch of email issues and this might be addressed at the same time.

**Comment by dhcole** [comment] 2015-02-09 23:40
Couldn't reproduce, but we now have a test for this.

**Comment by ultrasaurus** [comment] 2015-04-27 14:16
This happened 4 times last week on Open Opportunities

**Comment by dhcole** [comment] 2015-04-27 17:21
I've reviewed the production database... I see no clues about why this is still happening. 

Also, I am unable to reproduce this locally, though we continue to see the issue in production.

The code around authentication could be simplified ID users only based on `username` (email) instead of emails in the `userEmail` table. 

To find the source of this, I'd need to do a full code review of the authentication process, which could take a full day or so. Alternatively, I should be able to enforce uniqueness on the user models, so if someone triggers a duplicate account, it would return an error. I've avoided this because it's not a great user experience, but it would stop the problem from occurring until we're ready to commit to reviewing / refactoring user auth.å

@ultrasaurus should I prioritize the full review now? In the mean time, I'll get the error set up.

**Comment by dhcole** [comment] 2015-05-04 17:03
@ultrasaurus this is in today's milestone, but based on our last conversation, we were planning to wait on a full refactor since this is an inconvenience for admins but should have no noticeable impact on users.

Should we move out of the milestone or do you see an actionable path to resolving this that we should do this week?

**Comment by ultrasaurus** [comment] 2015-05-04 17:13
cleared the milestone

**Comment by ultrasaurus** [comment] 2015-06-03 14:44
this continues to happen about once per week

**Comment by dhcole** [comment] 2015-06-05 14:47
Duplicate accounts may cause log-in problems because the email address is the same for both. If the disabled duplicate account has a higher ID number, auth attempts will query that account and block the user.

To fix, when disabling a duplicated account, we should also remove / change the email address to something arbitrary so that it won't conflict with the appropriate account during sign in.

**Comment by dhcole** [comment] 2015-07-27 20:23
Closed by #902

**Closed by dhcole** 2015-07-27 20:23 UTC
Labels: bug, in progress, PR
