### ISSUE TITLE
As a user the task creation modal is confusing, disordered

### ISSUE THREAD

**Issue by brandtheisey** [18F/midas#713] opened 2015-04-15 20:07 UTC
I'd like to see two major changes to the task order modal.

1) *What problem are you trying to solve* -- to a novice user it's not clear that this field will be used as a title, it should say so.

2) The section of the modal where you enter the description is last on the create task process. In the create project process it is on the same page as the title.
![screen shot 2015-04-15 at 4 06 29 pm](https://cloud.githubusercontent.com/assets/7915386/7168173/705f50e6-e389-11e4-8fb4-3a77cc1fccb6.png)

The create task modal should mirror this arrangement, including the change to the title box.

**Comment by ultrasaurus** [comment] 2015-04-15 20:13
scroll to the bottom of https://github.com/18F/midas/issues/318 and let me know what you think of the proposed UI

**Comment by brandtheisey** [comment] 2015-04-16 17:31
ML & I both like the general design but think there are too many words. Would about a version where the instructions are hidable via a *more information* icon (or something like it)?

**Comment by ultrasaurus** [comment] 2015-04-16 19:03
noted in other issue, closing as duplicate of https://github.com/18F/midas/issues/318

**Closed by ultrasaurus** 2015-04-16 19:03 UTC
