### ISSUE TITLE
When an Opportunity is marked Completed, participants should receive an email

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#580] opened 2015-02-12 14:52 UTC
(Email sent once the Task Creator has marked the Opportunity complete)
```
To: Participant
CC: Task Creator 
Subject Line: [Task name] is complete — thank you!  

Hi [user’s name],

Congrats! You’ve successfully completed “[task name here].” Your profile has been updated to reflect your achievement. 

Thanks again,

The [_________] Team
```

Note: this depends on: https://github.com/18F/midas/issues/580

**Comment by LisaLNelson** [comment] 2015-02-12 16:48
https://www.surveymonkey.com/s/openoppsfy15

**Comment by dhcole** [comment] 2015-08-10 21:12
@ultrasaurus is this blocked by anything or can it move forward?

**Comment by dhcole** [comment] 2015-08-10 21:48
Email copy with the survey:

```md
(Email sent once the Task Creator has marked the Opportunity complete)

To: Participant
CC: Task Creator 
Subject Line: [Task name] is complete — thank you!  

Hi [user’s name],

Congrats! You’ve successfully completed “[task name here].” Your profile has been updated to reflect your achievement.

We at Open Opportunities are always looking for ways to make our program better. Please take a moment to complete this quick survey — your feedback will help us continue to improve your experience.

Thanks again,

The Open Opportunities Team


```

**Comment by dhcole** [comment] 2015-08-17 19:25
Duplicate of #819. Will track there.

**Closed by dhcole** 2015-08-17 19:25 UTC
