### ISSUE TITLE
Browse Tasks returns all tasks not in draft state on 1st load

### ISSUE THREAD

**Issue by brandtheisey** [18F/midas#605] opened 2015-02-23 21:05 UTC
Browse tasks returns all tasks not in draft state on 1st load.

It should only return users draft tasks and open tasks or just open tasks.

**Comment by dhcole** [comment] 2015-08-10 21:09
Tried to get around this problem with a refactor in #656.

Supporting better pagination and filtering could be addressed in #863

**Comment by dhcole** [comment] 2015-09-24 04:26
This is by design now and optimized.

**Closed by dhcole** 2015-09-24 04:26 UTC
