### ISSUE TITLE
As a task taker, I expect the number of opps advertised on the dashboard to match the opps I see when I search 'open' opps

### ISSUE THREAD

**Issue by awichman** [18F/midas#1018] opened 2015-09-25 14:24 UTC
The dashboard looks great!!!

As a task taker, I see that the dashboard tells me that there are 87 open opportunities right now. I would then expect to see 87 open tasks for the taking, but there are 11.

**Comment by jeremiak** [comment] 2015-09-25 14:30
Thanks for opening an issue @awichman!

I'm going to close this issue in favor of an existing one #1014 and we've actually already got a fix in #1016 so that should be live in the next release or two.

Background for why the issue is there: We're looking for all tasks that are *not* complete, but we *should* be looking for tasks that *are* open.

**Closed by jeremiak** 2015-09-25 14:30 UTC

**Comment by awichman** [comment] 2015-09-25 14:36
Oh great! Thanks @jeremiak!
