### ISSUE TITLE
All user query (new /api/user/all endpoint) slow on dev

### ISSUE THREAD

**Issue by sefk** [18F/midas#797] opened 2015-05-18 17:05 UTC
Look at the "network" tab on chrome developer tools when looking at the [people page](https://midas-dev.18f.us/people) on staging. You see time to first byte (TTFB) for "all" in the 600ms - 1000ms range. Only 15KB of data is being returned!

This isn't what I see in my dev environment, of course. 60ms to return 19KB. But that's localhost, quiet postgres server, artificial (demo) data.

To debug I would either need better test data (see #712) or access to staging.

**Comment by sefk** [comment] 2015-05-18 21:03
While I can't say for sure, it's very likely that the problem could be the Sails ORM doing a dumb query. [This gist is the Postgres log][pglog] when hitting ```/api/user/all``` on my dev environment (13 users each with a tag or two). 

  [pglog]: https://gist.github.com/sefk/800236501cfd6990f78d

While I haven't profiled this, line 6 of the gist certainly looks to be a potential culprit. Instead of an inner join, the sql generated does a subquery for every foreign key and then union's them all together. You could imagine that a query planner *might* be smart enough to notice and optimize this case but not only is that unlikely, but also unnecessary. 

Three options for proceeding 

1. **Waterline Fix.** I've searched the Waterline and Sails lists and there are several issues filed that may relate to this, but not sure. I'm wary of opening my own issue until I discuss with @dhcole and likely characterize this using their own schema / tests. My reading however makes me believe that this isn't some fix already made somewhere, not a quick & easy fix.

2. **Hand Join.** User.find(), then do TagEntity.find() and join ourselves. Ugly to have to do this but a) two queries would be much more efficient, b) it's more data btw app server and DB, but we can winnow that down before sending to the client, and c) it would still work with the file-based backend used for testing

3. **Hand query().** We can always write the sql ourselves and call query() on it, but that won't work on a non-sql backend, like one that we use while running unit tests. 

Personally I think the "hand join" option is what I'd lean toward, but I wouldn't do it until I had the same problem repro'ed in my own dev environment (see #712 again).

Note there's issue [#944](https://github.com/balderdashy/waterline/issues/944) that may be related but may not. That looks to be a memory issue at larger data sizes than we're seeing.

**Comment by dhcole** [comment] 2015-05-20 20:25
I can confirm I *do* see this on the production DB as well. It takes about 1000ms to respond to this endpoint.

It seems like running the query is relatively fast, but the node.js code to build the query is the big bottleneck. 

![screen shot 2015-05-20 at 4 07 22 pm](https://cloud.githubusercontent.com/assets/170641/7735603/47177224-ff0c-11e4-89d7-5a7e2bda98e2.png)

When I remove the `populate('tags')` method, I see response times around 150ms.

I think we have to resolve this at the waterline level. 2) above would be more complicated because we'd need to join across three tables, users, tagEntities, and the join table that links their IDs. I'm not sure if the join table is a sql-specific convention too, which would also introduce the same sql dependency issue as 3).

That being said, we're talking about 1 second to load a map of all users in the system. I don't think it's worth optimizing this endpoint at this time, but good to have this documented for when we grow and can address it. If no objections, I'll close this ticket.

**Comment by dhcole** [comment] 2015-05-21 16:25
Ok, we're going to icebox for now. We'll verify performance isn't much different on the production server when we deploy there and look into an upstream fix as time allows.

**Closed by dhcole** 2015-05-21 16:25 UTC
Labels: icebox
