### ISSUE TITLE
User interests/tags delete when photo upload fails

### ISSUE THREAD

**Issue by meiqimichelle** [18F/midas#926] opened 2015-07-29 15:26 UTC
In Firefox 39, when I tried to upload a photo (I didn't have one) to my profile, it did not display (perhaps related to #800). When I then hit 'save' (figuring it might be a refresh issue as in #800), my interests/tags deleted. I thought it was a fluke - took me a few tries to link the photo fail to the interest delete, but now I'm pretty sure that's what's happening.

So:
1. Edit profile
2. Try to upload photo, this visually fails in Firefox
3. Hit 'save'
4. On page reload, most tags will be gone. It left what looked like a default tag? (one tag called for UX)

**Comment by dhcole** [comment] 2015-07-30 22:22
Thanks for the report @meiqimichelle and sorry for the troubles. I'll take a look.

**Comment by awhig** [comment] 2015-08-14 04:10
#800 is fixed now. When fixing that, I could not reproduce this bug, where my interests were deleted. Maybe try this again, now that #800 is fixed?

**Closed** 2015-09-24 04:45 UTC
Labels: help wanted
